name: HyperSerialPico CI Build

on: [push]

jobs:

###########################
#### HyperSerialPico ######
###########################

  HyperSerialPico:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - board: pico
            chip: rp2040
            package: Pimoroni_Plasma_RP2040
          - board: pimoroni_plasma2350
            chip: rp2350
            package: Pimoroni_Plasma_RP2350

    steps:
    - uses: actions/checkout@v7.0.1
      with:
        submodules: recursive

    - name: Install GNU Arm Embedded Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '14.2.Rel1'

    - name: Build ${{ matrix.package }} custom firmware
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DTARGET_BOARD=${{ matrix.board }} ..
        cmake --build . --config Release --target HyperSerialPico_${{ matrix.chip }}_sk6812Cold_rev_multisegment_at_132
        zip -j ../firmware/${{ matrix.package }}.zip ../firmware/HyperSerialPico_${{ matrix.chip }}_sk6812Cold_rev_multisegment_at_132.uf2

    - uses: actions/upload-artifact@v7.0.1
      name: Upload ${{ matrix.package }} custom firmware
      with:
        name: ${{ matrix.package }}
        archive: ${{ startsWith(github.ref, 'refs/tags/') }}
        if-no-files-found: error
        path: firmware/${{ matrix.package }}.zip

################################
###### Publish Releases ########
################################

  publish:
    name: Publish Releases
    if: startsWith(github.event.ref, 'refs/tags')
    needs: [HyperSerialPico]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      # generate environment variables
      - name: Generate environment variables from version and tag
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "preRelease=false" >> $GITHUB_ENV

      # If version contains alpha or beta, mark draft release as pre-release
      - name: Mark release as pre-release
        if: contains(env.VERSION, 'alpha') || contains(env.VERSION, 'beta')
        run: echo "preRelease=true" >> $GITHUB_ENV

      - uses: actions/download-artifact@v8.0.1
        with:
          pattern: Pimoroni_Plasma_RP*
          merge-multiple: true

      # create draft release and upload artifacts
      - name: Create draft release
        uses: softprops/action-gh-release@v3.0.2
        with:
          name: HyperSerialPico ${{ env.VERSION }}
          tag_name: ${{ env.TAG }}
          files: |
            Pimoroni_Plasma_RP2040.zip
            Pimoroni_Plasma_RP2350.zip
          fail_on_unmatched_files: true
          draft: true
          prerelease: ${{ env.preRelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
